### ISSUE TITLE
1.0版本计划

### ISSUE THREAD

**Issue by vaynetian** [sgjsakura/CC98.Software#1]

**Comment by ES-SAL** [comment]
1、需要有一个下载用户的评论功能
2、软件介绍（破解补丁等使用方法）
3、同类软件推荐
4、软件分类、装机软件推荐

**Comment by zhating** [comment]
占个板凳：软件分类、软件下载量、评论区、同类软件、下载榜单

**Comment by vaynetian** [comment]
管理员审查

**Comment by wonderjeo** [comment]
1.精品推荐
2.优秀发布者列表
3.搜索软件
4.软件更新
5.软件发布入口

**Comment by vaynetian** [comment]
最新软件

**Comment by zhating** [comment]
上传的文件在一个缓冲区，管理员审查后进入用户可见的下载区

**Comment by vaynetian** [comment]
搜索条件：软件名 关键词

**Comment by vaynetian** [comment]
某个软件的信息：
用户需要做的：
1.软件名称 图标
2.软件分类
3.适用平台
4.软件功能简介
5.安装说明
生成的：
1.软件大小
2.更新时间
3.下载量
4.用户评论//1.0暂时搁置
5.当前状态：待审核/可下载
6.删除

**Comment by Dearkano** [comment]
上传的限制 搁置

**Comment by vaynetian** [comment]
主页：
1.搜索框
2.软件分类
3.最新软件
4.热门软件
5.推荐软件
6.优秀发布者
7.我要发布：ftp上传填写表单 /小文件网页直接上传  是否匿名
8.登录界面

**Comment by vaynetian** [comment]
软件分类页面：
有软件的目录
目录包含信息 1.名称2.图标3.大小4.下载量
链接进入某个软件详情界面

**Comment by vaynetian** [comment]
1.首页
2.搜索
3.软件详情
4.软件分类页面
5.我要发布
6.管理界面

**Comment by vaynetian** [comment]
管理界面：
负责推荐软件 优秀发布者

**Comment by zhating** [comment]
软件分类：
视频软件，
（播放器，格式转换）
聊天工具，
浏览器，
音乐软件，
安全杀毒，
系统工具，
（备份还原，硬件工具，桌面工具，数据恢复，系统优化，驱动工具）
下载工具，
办公软件，
（文档处理，办公常用）
图像图片，
编程工具，
（开发平台，辅助工具，运行库）
行业软件
（各个专用需要用到的软件）

**Comment by zhating** [comment]
![r5 u q 00m8 lw 2 70_o3](https://cloud.githubusercontent.com/assets/24840240/21568601/da4a35bc-cef0-11e6-8100-294062dcb9fc.png)
